# Generated by Django 4.1.11 on 2024-02-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0002_text_url_alter_text_created_by_alter_text_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
