# Generated by Django 4.1.11 on 2023-09-06 16:38

import datetime
from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 9, 6, 16, 38, 27, 730617),
                verbose_name="Post date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro",
            field=models.CharField(max_length=250),
        ),
    ]
