# Generated by Django 4.1.11 on 2023-09-06 17:11

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="authors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.author"
            ),
        ),
    ]
